### ISSUE TITLE
  | ValueError: certfile "ssl/cert" does not exist

### ISSUE THREAD

**Issue by zyxcambridge** [zhangqijun/deeplearningdemo#6]
WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 228, in run
demo_gpu_server_1  |     super().run()
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 72, in run
demo_gpu_server_1  |     Arbiter(self).run()
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 198, in run
demo_gpu_server_1  |     self.start()
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 155, in start
demo_gpu_server_1  |     self.LISTENERS = sock.create_sockets(self.cfg, self.log, fds)
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/sock.py", line 162, in create_sockets
demo_gpu_server_1  |     raise ValueError('certfile "%s" does not exist' % conf.certfile)
demo_gpu_server_1  | ValueError: certfile "ssl/cert" does not exist
demo_gpu_server_1  | [2020-01-09 10:43:17 +0800] [1] [INFO] Starting gunicorn 20.0.4
demo_gpu_server_1  | Traceback (most recent call last):
demo_gpu_server_1  |   File "/usr/local/bin/gunicorn", line 8, in <module>
demo_gpu_server_1  |     sys.exit(run())
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 58, in run
demo_gpu_server_1  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 228, in run
demo_gpu_server_1  |     super().run()
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 72, in run
demo_gpu_server_1  |     Arbiter(self).run()
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 198, in run
demo_gpu_server_1  |     self.start()
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 155, in start
demo_gpu_server_1  |     self.LISTENERS = sock.create_sockets(self.cfg, self.log, fds)
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/sock.py", line 162, in create_sockets
demo_gpu_server_1  |     raise ValueError('certfile "%s" does not exist' % conf.certfile)
demo_gpu_server_1  | ValueError: certfile "ssl/cert" does not exist
demo_gpu_server_1  | [2020-01-09 10:44:10 +0800] [1] [INFO] Starting gunicorn 20.0.4
demo_gpu_server_1  | Traceback (most recent call last):
demo_gpu_server_1  |   File "/usr/local/bin/gunicorn", line 8, in <module>
demo_gpu_server_1  |     sys.exit(run())
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 58, in run
demo_gpu_server_1  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 228, in run
demo_gpu_server_1  |     super().run()
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 72, in run
demo_gpu_server_1  |     Arbiter(self).run()
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 198, in run
demo_gpu_server_1  |     self.start()
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 155, in start
demo_gpu_server_1  |     self.LISTENERS = sock.create_sockets(self.cfg, self.log, fds)
demo_gpu_server_1  |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/sock.py", line 165, in create_sockets
demo_gpu_server_1  |     raise ValueError('keyfile "%s" does not exist' % conf.keyfile)
demo_gpu_server_1  | ValueError: keyfile "ssl/key" does not exist

**Comment by zhangqijun** [comment]
Your domain certificate should place in ssl folder。other wise change docker-compose.yml,make a http server
```
version: "3.3"

services:
  demo_cpu_server:
    restart: always
    stdin_open: true
    tty: true
    build: ./docker
    image: zzz9958123/demo_server:latest
    ports:
      - 5000:5000
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    command: 'gunicorn --workers=1 demo_cpu_server:app  --keyfile=ssl/key -b 0.0.0.0:5000  -t 600'
  demo_gpu_server:
    restart: always
    stdin_open: true
    tty: true
    build: ./docker
    image: zzz9958123/demo_server:latest
    ports:
      - 5001:5001
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    command: 'gunicorn --workers=1 demo_gpu_server:app  --keyfile=ssl/key -b 0.0.0.0:5001  -t 600'
```
